"""
generated_vocab.py — AUTO-GENERATED by vocab_generator.emit_literals().
Do NOT edit by hand; regenerate via `python demo_vocab.py`.
Source: llm | dimensions: 11 | terms: 71.
"""
from __future__ import annotations
from typing import Literal

AgeBandVocab = Literal["under_18", "18_29", "30_39", "40_49", "50_59", "60_plus", "unknown"]
SexVocab = Literal["male", "female", "unknown"]
HeartHealthVocab = Literal["unknown", "elite_athletic", "healthy_active", "average_sedentary", "at_risk"]
MedicalConditionsVocab = Literal["none", "hypertension", "arrhythmia", "diabetes_mellitus", "pregnancy", "thyroid_disorder", "cardiac_history", "unknown"]
OccupationVocab = Literal["unknown", "sedentary_office", "manual_labor", "shift_worker", "professional_athlete", "healthcare_professional", "student", "retired"]
GeographicLocationVocab = Literal["unknown", "temperate", "hot_arid", "hot_humid", "cold", "high_altitude"]
WeatherVocab = Literal["unknown", "thermoneutral", "cold_stress", "heat_stress", "high_humidity", "extreme_heatwave"]
WorkoutTypeVocab = Literal["unknown", "steady_state_cardio", "high_intensity_interval", "resistance_training", "low_impact_steady", "mind_body", "aquatic_exercise"]
WorkoutDurationVocab = Literal["unknown", "very_short", "short", "moderate", "long", "endurance"]
WorkoutLocationVocab = Literal["unknown", "indoor_gym", "home_workout", "outdoor_road", "outdoor_trail", "park", "pool", "open_water", "studio"]
SleepVocab = Literal["unknown", "restful", "adequate", "short", "fragmented", "irregular"]

# free-text alias -> controlled value, per dimension
ALIASES = {
  "age_band": {
    "pediatric": "under_18",
    "minor": "under_18",
    "child": "under_18",
    "adolescent": "under_18",
    "young_adult": "18_29",
    "early_adulthood": "18_29",
    "early_thirties": "30_39",
    "late_thirties": "30_39",
    "middle_age": "40_49",
    "forties": "40_49",
    "late_middle_age": "50_59",
    "fifties": "50_59",
    "senior": "60_plus",
    "elderly": "60_plus",
    "geriatric": "60_plus",
    "not_provided": "unknown",
    "missing": "unknown",
    "unspecified": "unknown"
  },
  "sex": {
    "man": "male",
    "masculine": "male",
    "biological male": "male",
    "woman": "female",
    "feminine": "female",
    "biological female": "female",
    "not_specified": "unknown",
    "missing": "unknown",
    "unassigned": "unknown"
  },
  "heart_health": {
    "not_available": "unknown",
    "missing_data": "unknown",
    "unclassified": "unknown",
    "high_performance": "elite_athletic",
    "cardiac_athlete": "elite_athletic",
    "superior_fitness": "elite_athletic",
    "fit": "healthy_active",
    "good_cardiovascular_health": "healthy_active",
    "physically_active": "healthy_active",
    "baseline": "average_sedentary",
    "standard": "average_sedentary",
    "moderate_fitness": "average_sedentary",
    "elevated_cardiac_risk": "at_risk",
    "poor_fitness": "at_risk",
    "deconditioned": "at_risk"
  },
  "medical_conditions": {
    "healthy": "none",
    "no_known_conditions": "none",
    "asymptomatic": "none",
    "high_blood_pressure": "hypertension",
    "essential_hypertension": "hypertension",
    "atrial_fibrillation": "arrhythmia",
    "afib": "arrhythmia",
    "tachycardia": "arrhythmia",
    "bradycardia": "arrhythmia",
    "irregular_heartbeat": "arrhythmia",
    "type_1_diabetes": "diabetes_mellitus",
    "type_2_diabetes": "diabetes_mellitus",
    "insulin_dependent": "diabetes_mellitus",
    "gestational_period": "pregnancy",
    "expecting": "pregnancy",
    "hyperthyroidism": "thyroid_disorder",
    "hypothyroidism": "thyroid_disorder",
    "graves_disease": "thyroid_disorder",
    "hashimotos": "thyroid_disorder",
    "post_myocardial_infarction": "cardiac_history",
    "heart_failure": "cardiac_history",
    "coronary_artery_disease": "cardiac_history",
    "not_provided": "unknown",
    "missing_data": "unknown",
    "unspecified": "unknown"
  },
  "occupation": {
    "not specified": "unknown",
    "missing": "unknown",
    "n/a": "unknown",
    "desk job": "sedentary_office",
    "white collar": "sedentary_office",
    "corporate": "sedentary_office",
    "blue collar": "manual_labor",
    "construction": "manual_labor",
    "physical trade": "manual_labor",
    "night shift": "shift_worker",
    "rotating schedule": "shift_worker",
    "irregular hours": "shift_worker",
    "elite athlete": "professional_athlete",
    "pro sports": "professional_athlete",
    "nurse": "healthcare_professional",
    "doctor": "healthcare_professional",
    "clinical staff": "healthcare_professional",
    "academic": "student",
    "university": "student",
    "senior": "retired",
    "non-working": "retired"
  },
  "geographic_location": {
    "not_specified": "unknown",
    "missing": "unknown",
    "n/a": "unknown",
    "moderate": "temperate",
    "mild_climate": "temperate",
    "continental": "temperate",
    "desert": "hot_arid",
    "dry_heat": "hot_arid",
    "xeric": "hot_arid",
    "tropical": "hot_humid",
    "equatorial": "hot_humid",
    "muggy": "hot_humid",
    "arctic": "cold",
    "polar": "cold",
    "subarctic": "cold",
    "mountainous": "high_altitude",
    "alpine": "high_altitude",
    "hypoxic": "high_altitude"
  },
  "weather": {
    "not_recorded": "unknown",
    "missing_data": "unknown",
    "n/a": "unknown",
    "comfortable": "thermoneutral",
    "mild": "thermoneutral",
    "temperate": "thermoneutral",
    "optimal": "thermoneutral",
    "chilly": "cold_stress",
    "freezing": "cold_stress",
    "cold_exposure": "cold_stress",
    "hot": "heat_stress",
    "warm": "heat_stress",
    "high_temperature": "heat_stress",
    "muggy": "high_humidity",
    "humid": "high_humidity",
    "damp": "high_humidity",
    "heat_index_extreme": "extreme_heatwave",
    "dangerous_heat": "extreme_heatwave"
  },
  "workout_type": {
    "not_recorded": "unknown",
    "missing": "unknown",
    "n/a": "unknown",
    "run": "steady_state_cardio",
    "jog": "steady_state_cardio",
    "cycle": "steady_state_cardio",
    "row": "steady_state_cardio",
    "elliptical": "steady_state_cardio",
    "hiit": "high_intensity_interval",
    "sprints": "high_intensity_interval",
    "circuit_training": "high_intensity_interval",
    "weightlifting": "resistance_training",
    "strength": "resistance_training",
    "bodybuilding": "resistance_training",
    "powerlifting": "resistance_training",
    "walk": "low_impact_steady",
    "hiking": "low_impact_steady",
    "leisure_cycling": "low_impact_steady",
    "yoga": "mind_body",
    "pilates": "mind_body",
    "stretching": "mind_body",
    "meditation": "mind_body",
    "swimming": "aquatic_exercise",
    "water_aerobics": "aquatic_exercise"
  },
  "workout_duration": {
    "not_recorded": "unknown",
    "missing_data": "unknown",
    "undefined": "unknown",
    "quick_session": "very_short",
    "warm_up_only": "very_short",
    "brief": "very_short",
    "standard_short": "short",
    "light_workout": "short",
    "typical_workout": "moderate",
    "average_session": "moderate",
    "extended_session": "long",
    "heavy_workout": "long",
    "marathon": "endurance",
    "ultra": "endurance",
    "prolonged_effort": "endurance"
  },
  "workout_location": {
    "not specified": "unknown",
    "n/a": "unknown",
    "missing": "unknown",
    "fitness center": "indoor_gym",
    "weight room": "indoor_gym",
    "health club": "indoor_gym",
    "living room": "home_workout",
    "garage gym": "home_workout",
    "home studio": "home_workout",
    "street": "outdoor_road",
    "pavement": "outdoor_road",
    "urban running": "outdoor_road",
    "hiking path": "outdoor_trail",
    "off-road": "outdoor_trail",
    "mountain trail": "outdoor_trail",
    "public green space": "park",
    "track": "park",
    "field": "park",
    "swimming pool": "pool",
    "natatorium": "pool",
    "lake": "open_water",
    "ocean": "open_water",
    "sea": "open_water",
    "yoga studio": "studio",
    "pilates studio": "studio",
    "group class": "studio"
  },
  "sleep": {
    "missing": "unknown",
    "no_data": "unknown",
    "untracked": "unknown",
    "deep_sleep": "restful",
    "high_quality": "restful",
    "restorative": "restful",
    "normal": "adequate",
    "sufficient": "adequate",
    "standard": "adequate",
    "insufficient": "short",
    "sleep_deprived": "short",
    "under_rested": "short",
    "interrupted": "fragmented",
    "restless": "fragmented",
    "broken": "fragmented",
    "inconsistent": "irregular",
    "circadian_mismatch": "irregular",
    "shift_work": "irregular"
  }
}

# controlled value -> physiological note, per dimension
NOTES = {
  "age_band": {
    "under_18": "Higher resting heart rate and greater HRV variability compared to adults due to developmental autonomic maturation.",
    "18_29": "Baseline period for peak physiological performance; HRV is typically at its lifetime maximum.",
    "30_39": "Onset of gradual decline in maximal heart rate and subtle reduction in parasympathetic tone.",
    "40_49": "Increased prevalence of age-related cardiovascular stiffening which begins to influence HRV recovery metrics.",
    "50_59": "Significant reduction in maximal heart rate; resting heart rate may stabilize but HRV complexity often decreases.",
    "60_plus": "Lowered maximal heart rate and reduced autonomic responsiveness; HRV values are generally lower and less dynamic.",
    "unknown": "Default state; requires population-average baseline assumptions which may lack precision."
  },
  "sex": {
    "male": "Generally associated with lower resting heart rates and slightly different autonomic nervous system baseline profiles compared to females.",
    "female": "Generally associated with higher resting heart rates and distinct HRV fluctuations influenced by hormonal cycles.",
    "unknown": "Indicates absence of biological sex data, requiring the use of population-averaged reference values for heart rate and HRV metrics."
  },
  "heart_health": {
    "unknown": "Baseline data insufficient to establish a cardiovascular fitness profile.",
    "elite_athletic": "Characterized by very low resting heart rate and high vagal tone, often showing rapid heart rate recovery.",
    "healthy_active": "Normal resting heart rate range with consistent HRV patterns indicating efficient autonomic nervous system regulation.",
    "average_sedentary": "Typical resting heart rate and HRV values for a non-athletic population; serves as the standard reference point.",
    "at_risk": "Often associated with higher resting heart rates and reduced HRV, potentially indicating autonomic imbalance or cardiovascular strain."
  },
  "medical_conditions": {
    "none": "Baseline physiological parameters follow standard age-adjusted normative ranges.",
    "hypertension": "Often associated with reduced HRV and elevated resting heart rate due to increased sympathetic tone.",
    "arrhythmia": "Directly disrupts R-R interval regularity, rendering standard HRV metrics unreliable.",
    "diabetes_mellitus": "Frequently leads to autonomic neuropathy, resulting in blunted heart rate variability and elevated resting heart rate.",
    "pregnancy": "Characterized by a progressive increase in resting heart rate and significant shifts in autonomic balance throughout trimesters.",
    "thyroid_disorder": "Hyperthyroidism typically elevates resting heart rate, while hypothyroidism may induce bradycardia.",
    "cardiac_history": "Structural heart changes often result in reduced cardiac reserve and altered autonomic regulation.",
    "unknown": "Data insufficient to determine physiological baseline adjustments."
  },
  "occupation": {
    "unknown": "Baseline metrics are treated as population averages due to lack of specific activity context.",
    "sedentary_office": "Characterized by low daily energy expenditure and potential for postural-related HRV suppression.",
    "manual_labor": "High physical load throughout the day leads to elevated resting heart rate and potential cumulative fatigue.",
    "shift_worker": "Circadian misalignment often results in blunted HRV and elevated heart rate during typical sleep windows.",
    "professional_athlete": "High vagal tone typically results in a significantly lower resting heart rate and higher baseline HRV.",
    "healthcare_professional": "High cognitive and emotional stress combined with irregular physical activity often leads to increased sympathetic dominance.",
    "student": "Irregular sleep patterns and high cognitive load can cause significant fluctuations in daily HRV.",
    "retired": "Baseline metrics are generally more stable but may reflect age-related changes in autonomic nervous system responsiveness."
  },
  "geographic_location": {
    "unknown": "Baseline physiological parameters are indeterminate without environmental context.",
    "temperate": "Serves as the standard reference for autonomic nervous system regulation without extreme thermal stress.",
    "hot_arid": "Increased resting heart rate due to peripheral vasodilation and fluid loss for evaporative cooling.",
    "hot_humid": "Elevated cardiovascular strain as high humidity limits sweat evaporation, increasing core temperature and heart rate.",
    "cold": "Initial increase in heart rate due to sympathetic activation and peripheral vasoconstriction to conserve core heat.",
    "high_altitude": "Persistent elevation in resting heart rate and reduced HRV due to chronic hypoxic stress and increased sympathetic tone."
  },
  "weather": {
    "unknown": "Baseline physiological state cannot be adjusted for environmental thermal stress.",
    "thermoneutral": "Minimal thermoregulatory demand; heart rate and HRV reflect resting metabolic baseline.",
    "cold_stress": "Peripheral vasoconstriction and shivering thermogenesis increase metabolic rate and heart rate.",
    "heat_stress": "Vasodilation and increased skin blood flow elevate heart rate to maintain cardiac output and cooling.",
    "high_humidity": "Reduced evaporative cooling efficiency forces higher heart rate to manage core temperature elevation.",
    "extreme_heatwave": "Significant cardiovascular strain; heart rate is elevated due to sustained thermoregulatory demand and potential dehydration."
  },
  "workout_type": {
    "unknown": "Baseline physiological state is undefined; no specific heart rate expectation.",
    "steady_state_cardio": "Characterized by a gradual rise to a stable heart rate plateau with predictable HRV suppression.",
    "high_intensity_interval": "Rapid heart rate spikes followed by incomplete recovery periods; significant autonomic nervous system strain.",
    "resistance_training": "Heart rate response is intermittent and influenced by Valsalva maneuvers and peripheral resistance.",
    "low_impact_steady": "Maintains heart rate near aerobic threshold with minimal HRV volatility compared to high-intensity efforts.",
    "mind_body": "Typically lowers heart rate and increases HRV through parasympathetic activation and controlled breathing.",
    "aquatic_exercise": "Hydrostatic pressure and horizontal body position result in lower resting heart rates compared to land-based equivalents."
  },
  "workout_duration": {
    "unknown": "Duration is unavailable; baseline heart rate variability cannot be adjusted for exercise load.",
    "very_short": "Duration is 1-15 minutes; minimal impact on long-term HRV recovery.",
    "short": "Duration is 16-30 minutes; moderate sympathetic activation with rapid return to baseline.",
    "moderate": "Duration is 31-60 minutes; significant metabolic demand requiring standard post-exercise recovery.",
    "long": "Duration is 61-120 minutes; sustained sympathetic dominance likely to suppress HRV for several hours.",
    "endurance": "Duration is 121+ minutes; high risk of autonomic nervous system fatigue and prolonged recovery requirements."
  },
  "workout_location": {
    "unknown": "Baseline physiological expectations remain neutral without environmental context.",
    "indoor_gym": "Controlled climate typically minimizes thermoregulatory stress on heart rate.",
    "home_workout": "Familiar environment often correlates with lower psychological stress markers.",
    "outdoor_road": "Exposure to traffic and uneven surfaces may increase sympathetic nervous system activation.",
    "outdoor_trail": "Variable terrain and elevation changes significantly increase heart rate variability demands.",
    "park": "Open air environments generally support stable heart rate recovery compared to urban heat islands.",
    "pool": "Hydrostatic pressure and horizontal body position lower resting heart rate compared to land-based exercise.",
    "open_water": "Cold water immersion and currents increase metabolic cost and heart rate response.",
    "studio": "Structured environments often involve guided breathing which can modulate HRV."
  },
  "sleep": {
    "unknown": "Baseline metrics cannot be established due to lack of overnight sensor coverage.",
    "restful": "Characterized by a pronounced nocturnal heart rate dip and high HRV stability, indicating optimal autonomic recovery.",
    "adequate": "Expected physiological baseline with a moderate heart rate decline and typical HRV fluctuations throughout the night.",
    "short": "Reduced duration limits the time available for parasympathetic dominance, often resulting in a higher average nocturnal heart rate.",
    "fragmented": "Frequent heart rate spikes and HRV drops suggest sympathetic nervous system arousal during the sleep cycle.",
    "irregular": "Variable sleep timing prevents the stabilization of circadian rhythms, leading to unpredictable heart rate and HRV baseline shifts."
  }
}
